### ISSUE TITLE
Differentiate between 'armeabi-v7a' and 'armeabi' architectures

### ISSUE THREAD

**Issue by Rikk** [android-police/apkmirror-public#48]
Currently, both "armeabi-v7a" and "armeabi" are displayed as "arm" which makes it harder for the user to choose the correct apk when both exist for the same app.

Thank you.

**Comment by Rikk** [comment]
'armv7a' is the same size of 'x86_64', but with one extra char we have cooler "arm-v7a". Maybe it could be "arm-neon" or similar, too.

Off topic, another issue with the site I see is the text overflow caused by long developer names or by the message "XX new variables added:...". I think it should be as easy to fix as adding a world-weary or word-break to the CSS.

**Comment by xewelmafi** [comment]
Nice

**Comment by Rikk** [comment]
Progress?

**Comment by Rikk** [comment]
Almost 3 months... Any decision about this?

**Comment by archon810** [comment]
Sorry, this issue is like #200 in our internal list of todos, so I can't promise a fix any time soon.

**Comment by archon810** [comment]
> Off topic, another issue with the site I see is the text overflow caused by long developer names or by the message "XX new variables added:...". I think it should be as easy to fix as adding a world-wrap or word-break to the CSS.

I believe we fixed that part.

**Comment by archon810** [comment]
This bug is now fixed.

We now differentiate between armeami and armeabi-v7a by using these shorthands: arm and arm-v7a.

This is done in APK details and variant tables, but not in titles to keep them short (there, it's still just "arm").

**Comment by Rikk** [comment]
Looks great. Thank you, Artem

**Comment by Rikk** [comment]
Detail: emails from upload approvals are still not using updated label.

**Comment by SeBsZ** [comment]
As @archon810 mentioned, we still show just 'arm' in all titles to keep them short. That means the title in the emails will also show the shorthand form.

**Comment by Rikk** [comment]
@SeBsZ thanks for the quick reply, nice to hear from you here.
I don't think it will make a difference in the case of emails regarding limit of space in titles, but it will avoid two emails (arm and arm-v7a) being tied up in the same thread ("conversation") in mail services like Gmail, because they have the same title. Anyway, in the body of the email I think it would make even more sense...

**Comment by SeBsZ** [comment]
@Rikk no problem. There's definitely no space issue in emails, it's just that the emails simply contain the title as it is shown on the website. We could definitely expand the email, or at least the subject to prevent the emails from being tied up in the same conversation. I'll let @archon810 decide. Thanks for the suggestion!

**Comment by Rikk** [comment]
Is this the only place these appear on the site, or are there other places too? In below scratch I don't think these extra 4 chars would be a problem:
![screenshot_2018-07-09 edit](https://user-images.githubusercontent.com/2916485/42446319-2dfa5c30-834c-11e8-9a49-deb40b4a4382.png)

**Comment by archon810** [comment]
I agree, the dropdown can definitely fit more descriptive names @SeBsZ.

**Comment by archon810** [comment]
@SeBsZ Have we ever resolved this?

**Comment by SeBsZ** [comment]
Of course:
![image](https://user-images.githubusercontent.com/5457531/48418998-1842c480-e757-11e8-83c2-1dda28b506ca.png)
